"use client";
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {creature,habitat,lighting,disposeScene} from '@/lib/three-world';
import type {World} from '@/lib/world';
function renderer(canvas:HTMLCanvasElement){const r=new T.WebGLRenderer({canvas,antialias:false,alpha:true,powerPreference:'low-power'});r.setPixelRatio(1);r.shadowMap.enabled=true;r.shadowMap.type=T.PCFShadowMap;r.toneMapping=T.ACESFilmicToneMapping;r.toneMappingExposure=1.1;return r}
export function Portrait3D({seed,large=false}:{seed:number;large?:boolean}){const canvas=useRef<HTMLCanvasElement>(null);useEffect(()=>{if(!canvas.current)return;let r:T.WebGLRenderer;try{r=renderer(canvas.current)}catch{return}r.setSize(large?140:64,large?166:76,false);const scene=new T.Scene();lighting(scene);const model=creature(seed);scene.add(model);const camera=new T.OrthographicCamera(-1.5,1.5,1.8,-1.8,.1,30);camera.position.set(0,1.5,8);camera.lookAt(0,1.35,0);let frame=0;const start=performance.now();function render(){if(document.hidden){if(large)frame=requestAnimationFrame(render);return}if(large){model.rotation.y=Math.sin((performance.now()-start)/2600)*.4}r.render(scene,camera);if(large)frame=requestAnimationFrame(render)}render();return()=>{cancelAnimationFrame(frame);disposeScene(scene);r.dispose();r.forceContextLoss()}},[seed,large]);return <canvas ref={canvas} aria-label="Procedurally generated 3D creature"/>}
export function World3D({world,selected,onSelect,event}:{world:World;selected:number;onSelect:(i:number)=>void;event:string}){const canvas=useRef<HTMLCanvasElement>(null);const latest=useRef({world,selected,event,onSelect});latest.current={world,selected,event,onSelect};const [error,setError]=useState('');
useEffect(()=>{if(!canvas.current)return;const el=canvas.current;let r:T.WebGLRenderer;try{r=renderer(el)}catch{setError('This 3D world requires WebGL. Try opening it in a browser with hardware acceleration.');return}const scene=new T.Scene();scene.background=new T.Color('#111719');lighting(scene);scene.add(habitat(world.seed));const camera=new T.PerspectiveCamera(35,1,.1,100);camera.position.set(1,10.5,18);const controls=new OrbitControls(camera,el);controls.target.set(0,.5,0);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=11;controls.maxDistance=29;controls.minPolarAngle=.35;controls.maxPolarAngle=Math.PI*.46;controls.update();
const models=world.residents.map((p,i)=>{const m=creature(p.seed);m.scale.setScalar(.72);m.position.set((p.x-360)/43,.13,(p.y-280)/32);m.userData.resident=i;m.traverse(o=>{o.userData.resident=i});scene.add(m);return m});
const ring=new T.Mesh(new T.RingGeometry(.55,.60,32),new T.MeshBasicMaterial({color:'#e0eca7',side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;scene.add(ring);
const rainGeo=new T.BufferGeometry();const drops=new Float32Array(240*3);for(let i=0;i<drops.length;i+=3){drops[i]=Math.sin(i*19)*8;drops[i+1]=(i%17)/2;drops[i+2]=Math.cos(i*7)*5}rainGeo.setAttribute('position',new T.BufferAttribute(drops,3));const rain=new T.Points(rainGeo,new T.PointsMaterial({color:'#b2c9d3',size:.055}));scene.add(rain);
const resize=()=>{const width=el.clientWidth,height=el.clientHeight;r.setSize(Math.max(1,Math.floor(width*.6)),Math.max(1,Math.floor(height*.6)),false);camera.aspect=width/Math.max(1,height);camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(el);resize();let frame=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let last=performance.now();
function render(now:number){if(document.hidden){last=now;frame=requestAnimationFrame(render);return}const dt=Math.min(.05,(now-last)/1000);last=now;const {world:w,selected:s,event:e}=latest.current;models.forEach((m,i)=>{const p=w.residents[i],tx=(p.x-360)/43,tz=(p.y-280)/32,dx=tx-m.position.x,dz=tz-m.position.z,moving=Math.abs(dx)+Math.abs(dz)>.04;m.position.x+=dx*Math.min(1,dt*2);m.position.z+=dz*Math.min(1,dt*2);m.position.y=.13+(!reduced&&moving?Math.abs(Math.sin(now*.012+i))*.10:0);m.rotation.y=(!reduced?Math.sin(now*.0008+i)*.10:0)+(moving?Math.atan2(dx,dz)*.18:0);m.rotation.z=!reduced&&p.action==='mischief'?Math.sin(now*.006)*.08:0});ring.position.set(models[s].position.x,.14,models[s].position.z);rain.visible=e==='A thunderstorm';if(rain.visible&&!reduced){for(let i=1;i<drops.length;i+=3){drops[i]-=dt*7;if(drops[i]<0)drops[i]=7}rainGeo.attributes.position.needsUpdate=true}controls.update();r.render(scene,camera);frame=requestAnimationFrame(render)}frame=requestAnimationFrame(render);
const raycaster=new T.Raycaster();let start={x:0,y:0};const down=(e:PointerEvent)=>{start={x:e.clientX,y:e.clientY}};const up=(e:PointerEvent)=>{if(Math.hypot(e.clientX-start.x,e.clientY-start.y)>5)return;const b=el.getBoundingClientRect();raycaster.setFromCamera(new T.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),camera);const hit=raycaster.intersectObjects(models,true)[0];if(hit)latest.current.onSelect(hit.object.userData.resident)};el.addEventListener('pointerdown',down);el.addEventListener('pointerup',up);
return()=>{cancelAnimationFrame(frame);observer.disconnect();el.removeEventListener('pointerdown',down);el.removeEventListener('pointerup',up);controls.dispose();disposeScene(scene);rainGeo.dispose();(rain.material as T.Material).dispose();r.dispose();r.forceContextLoss()};},[world.seed]);
return <div className="three-scene"><canvas ref={canvas} aria-label="Interactive generated 3D world. Drag to orbit, scroll to zoom, click a creature to inspect it."/>{error&&<p role="alert">{error}</p>}<span className="orbit-hint">DRAG TO ORBIT · SCROLL TO EXPLORE</span></div>}

